Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryMs.Data;
using LibraryMs.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using LibraryMs.Areas.Identity.Data;

namespace LibraryMs.Controllers
{
    [Authorize(Policy = "AllUsers")]
    public class BooksController : Controller
    {
        private readonly LibraryMsContext _context;
        private readonly INotyfService _notyf;
        private readonly UserManager<ApplicationUser> _userManager;
        public BooksController(LibraryMsContext context, 
            INotyfService notyf, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _notyf = notyf;
            _userManager = userManager;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString)
        {
            var books = from m in _context.Book
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                try
                {
                    books = books
                    .Where(s => s.SerialNumber!.Contains(searchString));

                    var libraryMsContext = books
                        .OrderBy(c => c.RegisterDate)
                        .Include(b => b.Form);
                    return View(await libraryMsContext.ToListAsync());

                }
                catch (Exception)
                {
                    throw;
                }
                
            }
            try
            {

                var libraryMsContext = books
                    .OrderBy(c => c.RegisterDate)
                    .Include(b => b.Form);
                return View(await libraryMsContext.ToListAsync());

            }
            catch (Exception)
            {
                throw;
            }

        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            { 

                var book = await _context.Book
                    .Include(b => b.Form)
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (book == null)
                {
                    return NotFound();
                }

                return View(book);
            }
            catch (Exception)
            {
                _notyf.Error("Something Went Wrong, Kindly Try Again!!!");
                return RedirectToAction(nameof(Index));

            }
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            try
            {
                ViewData["FormID"] = new SelectList(_context.Form, "Id", "Name");
                return View();

            }
            catch (Exception)
            {
                _notyf.Error("Something Went Wrong, Kindly Try Again!!!");
                return RedirectToAction(nameof(Index));

            }

        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,RegisterDate,Subject,SerialNumber,FormID")] Book book)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Checking if book already registered
                    if (_context.Book.Where(c => c.SerialNumber == book.SerialNumber).Any())
                    {
                        ViewData["FormID"] = new SelectList(_context.Form, "Id", "Name", book.FormID);
                        _notyf.Error("This Book Serial Number is Already Registered.");
                        return View(book);

                    }
                    var user = await _userManager.GetUserAsync(User);
                    book.RegisteredBy = user.StaffNumber;
                    book.RegisterDate = DateTime.Now;
                    _context.Add(book);
                    await _context.SaveChangesAsync();
                    _notyf.Success("Book Registered Successfully.");
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception)
                {
                    throw;
                }

            }
            else
            {
                try
                {
                    ViewData["FormID"] = new SelectList(_context.Form, "Id", "Name", book.FormID);
                    return View(book);

                }
                catch (Exception)
                {
                    _notyf.Error("Something Went Wrong, Kindly Try Again!!!");
                    return RedirectToAction(nameof(Index));

                }

            }
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                var book = await _context.Book.FindAsync(id);
                if (book == null)
                {
                    return NotFound();
                }
                ViewData["FormID"] = new SelectList(_context.Form, "Id", "Name", book.FormID);
                return View(book);

            }
            catch (Exception)
            {
                _notyf.Error("Something Went Wrong, Kindly Try Again!!!");
                return RedirectToAction(nameof(Index));

            }


        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,RegisterDate,Subject,SerialNumber,FormID")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Checking if book already registered
                    if (_context.Book.Where(c => c.SerialNumber == book.SerialNumber).Count()>1)
                    {
                        ViewData["FormID"] = new SelectList(_context.Form, "Id", "Name", book.FormID);
                        _notyf.Error("This Book Serial Number is Already Registered.");
                        return View(book);

                    }
                    _context.Update(book);
                    _notyf.Success("Book Updated Successfully.");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                try
                {
                    ViewData["FormID"] = new SelectList(_context.Form, "Id", "Name", book.FormID);
                    return View(book);

                }
                catch(Exception)
                {
                    throw;
                }
            }
            
        }

        // GET: Books/Delete/5
        /*
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Form)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
        */

        // POST: Books/Delete/5
        [Authorize(Policy = "PrincipalUsers")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            { 
                var book = await _context.Book.FindAsync(id);
                _context.Book.Remove(book);
                await _context.SaveChangesAsync();
                _notyf.Success("Book Deleted Successfully.");
                return RedirectToAction(nameof(Index));
            }
            catch( DbUpdateConcurrencyException)
            {
                throw;
            }
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.Id == id);
        }
    }
}

Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryMs.Data;
using LibraryMs.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;

namespace LibraryMs.Controllers
{
    [Authorize(Policy = "AllUsers")]
    public class FormsController : Controller
    {
        private readonly LibraryMsContext _context;
        private readonly INotyfService _notyf;
        public FormsController(LibraryMsContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        // GET: Forms
        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _context.Form.ToListAsync());

            }
            catch (Exception)
            {
                throw;
            }

        }

        // GET: Forms/Details/5
        /*
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _context.Form
                .FirstOrDefaultAsync(m => m.Id == id);
            if (form == null)
            {
                return NotFound();
            }

            return View(form);
        }
        */

        // GET: Forms/Create
        public IActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                throw;
            }

        }

        // POST: Forms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Form form)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (_context.Form.Where(c => c.Name == form.Name).Any())
                    {
                        _notyf.Error("This Form Name is Already Registered.");
                        return View(form);

                    }
                    _context.Add(form);
                    await _context.SaveChangesAsync();
                    _notyf.Success("Form Registered Successfully.");
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception)
                {
                    throw;
                }

            }
            else
            {
                try
                {
                    return View(form);

                }
                catch (Exception)
                {
                    throw;
                }
            }
            
        }

        [Authorize(Policy = "LibraryUsers, AdminUsers")]
        // GET: Forms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _context.Form.FindAsync(id);
            if (form == null)
            {
                return NotFound();
            }
            return View(form);
        }

        // POST: Forms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Policy = "LibraryUsers, AdminUsers")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Form form)
        {
            if (id != form.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(form);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormExists(form.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }

        // GET: Forms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _context.Form
                .FirstOrDefaultAsync(m => m.Id == id);
            if (form == null)
            {
                return NotFound();
            }

            return View(form);
        }

        // POST: Forms/Delete/5
        [Authorize(Policy = "Admin&PrincipalUsers")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _context.Form.FindAsync(id);
            if (form == null)
            {
                return NotFound();
            }
            try
            { 
            _context.Form.Remove(form);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }
        }

        private bool FormExists(int id)
        {
            return _context.Form.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryMs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
    <link rel="stylesheet" href="~/lib/Font-Awesome/css/regular.min.css">
    <link rel="stylesheet" href="~/lib/Font-Awesome/css/solid.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryMs.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-success text-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white display-6" asp-area="" asp-controller="Borrowings" asp-action="Index">LIBRARY MANAGEMENT SYSTEM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row main-container">
            <div class="col-md-3 side-menu">
                 <partial name="_Navigation.cshtml" />
            </div>
            <div class="col-md-9 mt-4 pt-2 main-menu">
                @RenderBody()
            </div>
        </div>
    </div>  
        <footer class="border-top footer text-muted">
       
            <div class="container text-black text-center">
                &copy; 2021 - AMOS ICT SERVICES | 0702240787 | amosndonga@gmail.com
            </div>
        </footer>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Navigation.cshtml
<ul class="mt-3 " id="myNav">
                    <li class="nav-item myNavItem">
                        <a class="nav-link text-white" asp-area="" asp-controller="Borrowings" asp-action="Index"><i class="fas fa-bars mx-1"></i> Issuance/Return Requests</a>
                    </li>
                     <li class="nav-item  myNavItem">
                        <a class="nav-link text-white" asp-area="" asp-controller="Books" asp-action="Index"><i class="fas fa-book mx-1"></i> Manage Books</a>
                    </li>
                    <li class="nav-item myNavItem">
                        <a class="nav-link text-white" asp-area="" asp-controller="Students" asp-action="Index"><i class="fas fa-user-graduate mx-1"></i> Manage Students</a>
                    </li>

                    <li class="nav-item myNavItem">
                        <a class="nav-link text-white" asp-area="" asp-controller="Forms" asp-action="Index"><i class="fas fa-school mx-1"></i> Manage Student Forms </a>
                    </li>
                    <li class="nav-item myNavItem">
                        <a class="nav-link text-white" asp-area="" asp-controller="Borrowings" asp-action="OverDue"><i class="fas fa-bars mx-1"></i>OverDue Issuance </a>
                    </li>
                     <li class="nav-item myNavItem">
                        <a class="nav-link text-white" asp-area="" asp-controller="Borrowings" asp-action="IssuanceHistory"><i class="fas fa-bars mx-1"></i> Issuance&Return History </a>
                    </li>
</ul>