Models/Borrowing.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace LibraryMs.Models
{
    public class Borrowing
    {
        [Key]
        public int Id { get; set; }
        public int StudentID { get; set; }
        public int BookID { get; set; }

        [Display(Name = "Issue Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime RegisterDate { get; set; }
        [Display(Name = "Issued")]
        public string Issued { get; set; } = "Yes";
        [Display(Name = "Due Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime ReturnDate { get; set; }

        [Display(Name = "Returned Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? ReturnedDate { get; set; }


        [Display(Name = "Issuing Officer")]
        public string IssuedBy { get; set; } = "Yes";

        [Display(Name = "Returning Officer")]
        public string ReturnedBy { get; set; } = "Yes";


        // Navigation Properties
        [Display(Name = "Student No.")]
        public Student CurrentStudent { get; set; }
        [Display(Name = "Book Serial No.")]
        public Book CurrentBook { get; set; }

    }
}

Controllers/BorrowingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryMs.Data;
using LibraryMs.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using LibraryMs.Areas.Identity.Data;
using OfficeOpenXml;

namespace LibraryMs.Controllers
{
    [Authorize(Policy = "AllUsers")]
    public class BorrowingsController : Controller
    {
        // ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
        private readonly LibraryMsContext _context;

        private readonly INotyfService _notyf;
        private readonly UserManager<ApplicationUser> _userManager;
        
        public BorrowingsController(
            LibraryMsContext context, 
            INotyfService notyf, 
            UserManager<ApplicationUser> userManager
            )
        {
            _context = context;
            _notyf = notyf;
            _userManager = userManager;
           
        }

        // GET: Borrowings
        public async Task<IActionResult> Index(string searchString)
        {

            var borrowings = from m in _context.Borrowing
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                try
                { 
                borrowings = borrowings.Where(b => b.Issued == "Yes")
                    .Include(b => b.CurrentBook)
                    .Where(o => o.CurrentBook.SerialNumber.Contains(searchString))
                    .Include(b => b.CurrentStudent);
                }
                catch(Exception)
                {
                    throw;
                }
            }
            try
            { 
            var libraryMsContext = borrowings.Where(b => b.Issued == "Yes")
                .Include(b => b.CurrentBook)
                .Include(b => b.CurrentStudent);

            //  _notyf.Success("Success Notification");
            return View(await libraryMsContext.ToListAsync());
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: Borrowings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            { 

            var borrowing = await _context.Borrowing
                .Include(b => b.CurrentBook)
                .Include(b => b.CurrentStudent)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (borrowing == null)
            {
                return NotFound();
            }

            return View(borrowing);
            }
            catch (Exception)
            {
                _notyf.Error("Something Went Wrong, Kindly Try Again!!!");
                return RedirectToAction(nameof(Index));

            }
        }

        // GET: Borrowings/Create
        public IActionResult Create()
        {
            try
            {
            ViewData["BookID"] = new SelectList(_context.Book, "Id", "SerialNumber");
            ViewData["StudentID"] = new SelectList(_context.Student, "Id", "AdminNumber");
            return View();
            }
            catch(Exception)
            {
                _notyf.Error("Something Went Wrong, Kindly Try Again!!!");
                return RedirectToAction(nameof(Index));

            }
        }

        // POST: Borrowings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentID,BookID,RegisterDate, ReturnDate")] Borrowing borrowing)
        {
            // checking if model valid
            if (ModelState.IsValid)
            {
                // check if book already issued
                if(_context.Borrowing.Where(c => c.BookID == borrowing.BookID).Where(c => c.Issued == "Yes").Any())
                {
                    ViewData["BookID"] = new SelectList(_context.Book, "Id", "SerialNumber", borrowing.BookID);
                    ViewData["StudentID"] = new SelectList(_context.Student, "Id", "AdminNumber", borrowing.StudentID);
                    _notyf.Error("This Book is Already Issued to Another Student.");
                    return View(borrowing);

                }
                //checking if Due date greater than today,now
                if(borrowing.ReturnDate <= DateTime.Now)
                {
                     ViewData["BookID"] = new SelectList(_context.Book, "Id", "SerialNumber", borrowing.BookID);
                     ViewData["StudentID"] = new SelectList(_context.Student, "Id", "AdminNumber", borrowing.StudentID);
                    _notyf.Error("Due Date Must Be Greater Than or Equals To Todays Date.");
                    return View(borrowing);
                    
                }
                try
                {
                    var user = await _userManager.GetUserAsync(User);
                    borrowing.Issued = "Yes";
                    borrowing.RegisterDate = DateTime.Now;
                    borrowing.IssuedBy = user.StaffNumber;
                    _context.Add(borrowing);
                    await _context.SaveChangesAsync();
                    _notyf.Success("Book Issued Successfully.");
                    return RedirectToAction(nameof(Index));
                }
                catch( Exception)
                 {
                    _notyf.Error("Something Went Wrong, Kindly Try Again!!!");
                    return RedirectToAction(nameof(Index));

                }
            }
            else
            { 
                try
                {
                ViewData["BookID"] = new SelectList(_context.Book, "Id", "SerialNumber", borrowing.BookID);
                ViewData["StudentID"] = new SelectList(_context.Student, "Id", "AdminNumber", borrowing.StudentID);
                _notyf.Error("Kindly Make sure The Form is Correctly Filled!!!");
                return View(borrowing);
                }
                catch (Exception)
                {
                    _notyf.Error("Something Went Wrong, Kindly Try Again!!!");
                    return RedirectToAction(nameof(Index));

                }
            }
        }

        // GET: Borrowings/Edit/5
        /*
       
        */

        [HttpPost, ActionName("Return")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Returned_Book(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var borrowing = await _context.Borrowing.FindAsync(id);
                borrowing.Issued = "No";
                borrowing.ReturnedDate = DateTime.Now;
                borrowing.ReturnedBy = user.StaffNumber;
                await _context.SaveChangesAsync();
                _notyf.Success("Book Returned Successfully.");
                return RedirectToAction(nameof(Index));

            }
            catch(Exception)
            {
                _notyf.Error("Book Returned Unsuccessfully, Kindly try again.");
                return RedirectToAction(nameof(Index));
            }
            
        }
        public async Task<IActionResult> IssuanceHistory(string searchString)
        {
            var borrowings = from m in _context.Borrowing
                             select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                try
                {
                    borrowings = borrowings.Where(b => b.Issued == "No")
                        .Include(b => b.CurrentBook)
                        .Where(o => o.CurrentBook.SerialNumber.Contains(searchString))
                        .Include(b => b.CurrentStudent);
                }
                catch (Exception)
                {
                    throw;
                }
            }
            try
            {
                var libraryMsContext = borrowings.Where(b => b.Issued == "No")
                    .Include(b => b.CurrentBook)
                    .Include(b => b.CurrentStudent);
                return View(await libraryMsContext.ToListAsync());
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<IActionResult> OverDue(string searchString)
        {
            var borrowings = from m in _context.Borrowing
                             select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                try
                {
                    borrowings = borrowings
                        .Where(b => b.Issued == "Yes")
                        .Where(b => b.ReturnDate <= DateTime.Now)
                        .Include(b => b.CurrentBook)
                        .Where(o => o.CurrentBook.SerialNumber.Contains(searchString))
                        .Include(b => b.CurrentStudent);
                }
                catch (Exception)
                {
                    throw;
                }
            }
            try
            {
                var libraryMsContext = borrowings
                    .Where(b => b.Issued == "Yes")
                    .Where(b => b.ReturnDate <= DateTime.Now)
                    .Include(b => b.CurrentBook)
                    .Include(b => b.CurrentStudent);
                return View(await libraryMsContext.ToListAsync());
            }
            catch (Exception)
            {
                throw;
            }
        }


        private bool BorrowingExists(int id)
        {

Views/Borrowings/Create.cshtml
@model LibraryMs.Models.Borrowing

@{
    ViewData["Title"] = "Issue Book";
}


<div class="container-fluid">
<p class="display-6">ISSUE BOOK</p>

<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row my-3">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="StudentID" class="control-label">Student ADMIN NO.</label>
                        <select asp-for="StudentID" class ="form-control" asp-items="ViewBag.StudentID"></select>
                    </div>
                    
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="BookID" class="control-label">Book Serial NO.</label>
                        <select asp-for="BookID" class ="form-control" asp-items="ViewBag.BookID"></select>
                    </div>
                </div>
            </div>
            <div class="row my-3">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="RegisterDate" class="control-label"></label>
                        <input asp-for="RegisterDate" class="form-control" />
                        <span asp-validation-for="RegisterDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="ReturnDate" class="control-label"></label>
                        <input asp-for="ReturnDate" class="form-control" />
                        <span asp-validation-for="ReturnDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Issue Book" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-success my-3 py-2">Back to Listings</a>
</div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Borrowings/Delete.cshtml
@model LibraryMs.Models.Borrowing

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Borrowing</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentStudent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentStudent.AdminNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentBook)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentBook.SerialNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Borrowings/Details.cshtml
@model LibraryMs.Models.Borrowing

@{
    ViewData["Title"] = "Issuance Details";
}



<div class="container-fluid">
    <p class="display-6">ISSUANCE DETAILS</p>
    <hr />
    <dl class="row table-body">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssuedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssuedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentStudent.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentStudent.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentStudent.AdminNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentStudent.AdminNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentBook.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentBook.Title)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentBook.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentBook.SerialNumber)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentStudent.Form.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentStudent.Form.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-success mt-3">Back to List</a>
</div>

Views/Borrowings/Edit.cshtml
@model LibraryMs.Models.Borrowing

@{
    ViewData["Title"] = "Edit Borrowings";
}
<div class="container-fluid">
<p class="display-6">EDIT ISSUED BOOKS</p>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="StudentID" class="control-label"></label>
                <select asp-for="StudentID" class="form-control" asp-items="ViewBag.StudentID"></select>
                <span asp-validation-for="StudentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookID" class="control-label"></label>
                <select asp-for="BookID" class="form-control" asp-items="ViewBag.BookID"></select>
                <span asp-validation-for="BookID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisterDate" class="control-label"></label>
                <input asp-for="RegisterDate" class="form-control" />
                <span asp-validation-for="RegisterDate" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save Changes" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-success mt-3">Back to List</a>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Borrowings/Index.cshtml
@model IEnumerable<LibraryMs.Models.Borrowing>

@{
    ViewData["Title"] = "Issued Books";
}

<div class="container-fluid">
    <p class="display-6">ISSUED BOOKS</p>
    <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <form method="get" class="row" asp-controller="Borrowings" asp-action="Index">
                        <div class="col-md-3">
                                <label class="col-form-label">Book Serial No.</label>
                        </div>
                        <div class="col-md-7">
                                 <input type="text" name="SearchString" class="form-control" required />
                        </div>
                        <div class="col-md-2">
                             <button type="submit" class="btn btn-primary mb-3">Search</button>
                        </div>
   
                   </form>
               </div>
               <div class="col-md-4 text-end">
                    <p>
                      <a asp-action="Create" class="btn btn-success"> <i class="fas fa-plus" aria-hidden="true"></i> Issue Book</a>
                  </p>
               </div>
            </div>
            <a  asp-controller= "ExcelReport" asp-action="BorrowingReport" class="btn btn-warning"> <i class="fas fa-expand px-1" aria-hidden="true"></i>Export To CSV</a>
     </div>
        <hr />
    <table class="table ">
        <thead class="table-head">
            <tr>
                <th>#</th>
                <th>
                    @Html.DisplayNameFor(model => model.RegisterDate)
                </th>
               
                <th>
                    @Html.DisplayNameFor(model => model.CurrentStudent.AdminNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentBook.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentBook.SerialNumber)
                </th>
                
                <th>
                    @Html.DisplayNameFor(model => model.Issued)
                </th>
                 <th>@Html.DisplayNameFor(model => model.ReturnDate)</th>
                 <th></th>
            </tr>
        </thead>
        <tbody class="table-body">
@if(Model != null)
    {
        int counter = 1;
    foreach (var item in Model) {
            var tm = "#myModal" + item.Id;
            var mid = "myModal" + item.Id;
            <tr>
                <td>@counter</td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegisterDate)
                </td>
                 
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentStudent.AdminNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentBook.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentBook.SerialNumber)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Issued)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReturnDate)
                </td>
                <td>
                   <!--<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">Edit</a> -->
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary">Details</a>
                    <!-- Button trigger modal -->
                     <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="@tm">
                    Return Book
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="@mid" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"  aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                   <h5 class="modal-title" id="staticBackdropLabel">Return Confirmation</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">     
                                     <p class="my-3">Are you sure you want to Return this Book?</p>
                                        <form method="post" asp-controller="Borrowings"  asp-action="Return" asp-route-id="@item.Id" >
                                           <button type="submit" class="btn btn-danger mx-2">Return </button>
                                           <button type="button" class="btn btn-success mx-2" data-bs-dismiss="modal">Cancel</button>
                                        </form>
                                </div>
                                <div class="modal-footer">
                                
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            counter++;
    }
}
        </tbody>
    </table>
</div>

Views/Borrowings/IssuanceHistory.cshtml
@model IEnumerable<LibraryMs.Models.Borrowing>

@{
    ViewData["Title"] = "Issuance History";
}

<div class="container-fluid">
    <p class="display-6">ISSUANCE HISTORY</p>
    <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <form method="get" class="row" asp-controller="Borrowings" asp-action="IssuanceHistory">
                        <div class="col-md-3">
                                <label class="col-form-label">Book Serial No.</label>
                        </div>
                        <div class="col-md-7">
                                 <input type="text" name="SearchString" class="form-control" required />
                        </div>
                        <div class="col-md-2">
                             <button type="submit" class="btn btn-primary mb-3">Search</button>
                        </div>
   
                   </form>
               </div>
               
            </div>
        </div>
        <hr />
    <table class="table ">
        <thead class="table-head">
            <tr>
                <th>#</th>
                <th>
                    @Html.DisplayNameFor(model => model.RegisterDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IssuedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentStudent.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentStudent.AdminNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentBook.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentBook.SerialNumber)
                </th>
                
                <th>
                    @Html.DisplayNameFor(model => model.Issued)
                </th>
                <th>@Html.DisplayNameFor(model => model.ReturnDate)</th>
                <th>@Html.DisplayNameFor(model => model.ReturnedDate)</th>
                <th>@Html.DisplayNameFor(model => model.ReturnedBy)</th>
                 
            </tr>
        </thead>
        <tbody class="table-body">
@if(Model != null)
    {
        int counter = 1;
    foreach (var item in Model) {
            var tm = "#myModal" + item.Id;
            var mid = "myModal" + item.Id;
            <tr>
                <td>@counter</td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegisterDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IssuedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentStudent.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentStudent.AdminNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentBook.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentBook.SerialNumber)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.Issued)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReturnDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReturnedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReturnedBy)
                </td>
            </tr>
            counter++;
    }
}
        </tbody>
    </table>
</div>

Views/Borrowings/OverDue.cshtml
@model IEnumerable<LibraryMs.Models.Borrowing>

@{
    ViewData["Title"] = "OverDue Issuance";
}

<div class="container-fluid">
    <p class="display-6">OVERDUE ISSUANCE</p>
    <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <form method="get" class="row" asp-controller="Borrowings" asp-action="OverDue">
                        <div class="col-md-3">
                                <label class="col-form-label">Book Serial No.</label>
                        </div>
                        <div class="col-md-7">
                                 <input type="text" name="SearchString" class="form-control" required />
                        </div>
                        <div class="col-md-2">
                             <button type="submit" class="btn btn-primary mb-3">Search</button>
                        </div>
   
                   </form>
               </div>
               <div class="col-md-3 offset-1 justify-content-end">
                   <a  asp-controller= "ExcelReport" asp-action="OverDueReport" class="btn btn-warning"> <i class="fas fa-expand px-1" aria-hidden="true"></i>Export To Excel</a>
               </div>
               
            </div>
            
        </div>
        <hr />
    <table class="table ">
        <thead class="table-head">
            <tr>
                <th>#</th>
                <th>
                    @Html.DisplayNameFor(model => model.RegisterDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IssuedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentStudent.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentStudent.AdminNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentBook.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentBook.SerialNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Issued)
                </th>
                 <th>@Html.DisplayNameFor(model => model.ReturnDate)</th>
                 <th></th>
            </tr>
        </thead>
        <tbody class="table-body">
@if(Model != null)
    {
        int counter = 1;
    foreach (var item in Model) {
            var tm = "#myModal" + item.Id;
            var mid = "myModal" + item.Id;
            <tr>
                <td>@counter</td>
                <td>
                    <p class="btn btn-secondary">@Html.DisplayFor(modelItem => item.RegisterDate)</p>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IssuedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentStudent.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentStudent.AdminNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentBook.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentBook.SerialNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Issued)
                </td>
                <td >
                    <p class="btn btn-danger">@Html.DisplayFor(modelItem => item.ReturnDate)</p> 
                </td>
                <td>
                    
                </td>
            </tr>
            counter++;
    }
}
        </tbody>
    </table>
</div>